# Generated by Django 2.0.4 on 2018-04-26 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=125)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=250, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('descriptions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('total_ticket', models.IntegerField()),
                ('ticket_date', models.DateTimeField()),
                ('location', models.CharField(default='Jakarta', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('descriptions', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=150)),
                ('durations', models.CharField(max_length=4, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_transaction',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_info',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('no_telp', models.CharField(max_length=15, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('code_pos', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='User_image/User-Default.jpg', upload_to='User_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_for',
            field=models.ManyToManyField(to='music.Music'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Event'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
