# Generated by Django 2.0.4 on 2018-04-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=150)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('total_ticket', models.IntegerField()),
                ('ticket_date', models.DateTimeField()),
                ('location', models.CharField(default='Jakarta', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('descriptions', models.CharField(max_length=250)),
                ('ticket_for', models.ManyToManyField(to='music.Music')),
            ],
        ),
    ]
