# Generated by Django 2.0.4 on 2018-04-22 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=125)),
                ('release_date', models.DateField(default=datetime.date(2018, 4, 22))),
                ('genre', models.CharField(max_length=250, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('descriptions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('total_ticket', models.IntegerField()),
                ('ticket_date', models.DateTimeField()),
                ('location', models.CharField(default='Jakarta', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('descriptions', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('nameapp', models.CharField(max_length=150)),
                ('durations', models.CharField(max_length=4, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_for',
            field=models.ManyToManyField(to='music.Music'),
        ),
    ]
