# Generated by Django 2.0.4 on 2018-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
