# Generated by Django 2.0.4 on 2018-04-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180424_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='music.Event'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ticket_buyed',
            field=models.IntegerField(null=True),
        ),
    ]
