# Generated by Django 2.0.4 on 2018-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_ticket_transaction_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_transaction',
            name='total_purchase',
            field=models.IntegerField(null=True),
        ),
    ]
