# Generated by Django 2.0.4 on 2018-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
