# Generated by Django 2.0.4 on 2018-04-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180424_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='music.Event'),
        ),
    ]
