# Generated by Django 2.0.4 on 2018-04-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_auto_20180425_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('idapp', models.AutoField(primary_key=True, serialize=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
