# Generated by Django 2.0.4 on 2018-04-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_transaction',
            old_name='total_buy',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='ticket_transaction',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticket_transaction',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket_transaction',
            name='code_pos',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket_transaction',
            name='no_telp',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket_transaction',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
